GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/1
###
DELETE http://localhost:3001/api/persons/66019781c70cfccf31bf5a0f HTTP/1.1

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-243563"
}

###
PUT http://localhost:3001/api/persons/660205be3867adbb7f0e58ce
Content-Type: application/json

{
    "number": "98765"
}